### ISSUE TITLE
psdoverlaypanel Directive not functioning

### ISSUE THREAD

**Issue by karim-mamdouh** [maitrungduc1410/primeng-shadowdom-directives#15]
Hello,

Please find the video below for issue

https://github.com/maitrungduc1410/primeng-shadowdom-directives/assets/79006178/619e06c5-5bc9-4b1f-8026-dab8e95e5617

Versions:

 "@angular/animations": "~16.1.0",
 "@angular/common": "~16.1.0",
 "@angular/compiler": "~16.1.0",
 "@angular/core": "~16.1.0",
 "primeng": "^16.0.2",
 "primeng-shadowdom-directives": "^1.0.1",

**Comment by maitrungduc1410** [comment]
Thanks for reporting issue, I'll check this and get back to you soon

**Comment by karim-mamdouh-cin** [comment]
Actually I found a way to fix it, I added the button as target for the toggle functions & then it worked perfectly

![image](https://github.com/maitrungduc1410/primeng-shadowdom-directives/assets/144590261/2e2adedc-9bdc-4ea7-8c78-9e41d0d9c2a4)

**Comment by maitrungduc1410** [comment]
It's weird that you have to specify the target.

In this case the target can be ignored because for second parameter it'll default to event.target which is equal to #target here.


![image](https://github.com/maitrungduc1410/primeng-shadowdom-directives/assets/16630193/a9775af5-e777-45e6-9a1f-7b11629e3ceb)

Can you check the demo app of this lib, in there I have examples for all cases

But yes, can go with your way first. I'll do some test this weekend.

**Comment by maitrungduc1410** [comment]
Btw, can you check package-lock and provide exact version for all related dependencies? Then I'll just use the same

**Comment by maitrungduc1410** [comment]
I checked, it's working really fine with same dependencies as you,  maybe you should try create a fresh new screen/component and add the overlay to test, try to not apply any class/style during testing:

https://github.com/maitrungduc1410/primeng-shadowdom-directives/assets/16630193/ecf454c3-590f-4217-a2e2-a7903852663e
