### ISSUE TITLE
[Question] How does this package work, roughly?

### ISSUE THREAD

**Issue by papb** [maitrungduc1410/primeng-shadowdom-directives#5]
Thank you for this package! I am curious as what is this package doing, roughly, I tried navigating the code but I found it complex. Can you say roughly what is the idea behind it? What is the core problem in PrimeNG that makes its overlays not work well with Shadow DOM?

Thank you :rocket:

**Comment by papb** [comment]
Hmm I found [this comment](https://github.com/primefaces/primeng/issues/9471#issuecomment-885542201), it explains the core of it, thanks. Is it still accurate? Did you have to do more tweaks to support other components since then? (over one year has passed since your comment).

**Comment by papb** [comment]
In particular, I am still curious as to why you had to create one new directive for each component. Is it because this is a separate module? Would it be possible to fix this "in the root cause", at a single place, if you were to make a PR on PrimeNG itself?

**Comment by maitrungduc1410** [comment]
I'll answer your questions one by one.

> How does this package work, roughly

Basic idea has 2 parts:
- Update `domhandler.ts` a bit (small piece of code as described [here](https://github.com/primefaces/primeng/issues/9471#issuecomment-885542201)) to handle ShadowDOM
- Reading implementation of each "overlay" component from PrimeNG, if in any place it assumes Real DOM then we need to add more logics to handle Shadow DOM

Note: If you notice we need to have `connectedoverlayscrollhandler.ts` also, since primeNG components use `connectedoverlayscrollhandler` directly and the file imports `domhandler.ts`. But I don't change anything from `connectedoverlayscrollhandler`, just need it since its dependence with `domhandler.ts`

**Comment by maitrungduc1410** [comment]
> I am still curious as to why you had to create one new directive for each component

As mention above, I need to go through implementation of each PrimeNG component (by reading their source code), see if any place needs to be updated.

Some time just simple change, some time it needs more effort, depends on how it's implemented. Sometimes the change is repetitive, so we can share, for example [here](https://github.com/maitrungduc1410/primeng-shadowdom-directives/blob/94a7e3b59ef75b0e883ef7a63feba75e53d67807/projects/primeng-shadowdom-directives/src/directives/dropdown.ts#L5-L23), but usually it's not same for each component, that's why I need to create separate directives for each of them to handle ShadowDOM

Usually it's adding more "if/else" to handle more cases. Remember that I "add more", so the default logics is still there, no change.

**Comment by papb** [comment]
Thank you very much for the fast replies :rocket:

> for example [here](https://github.com/maitrungduc1410/primeng-shadowdom-directives/blob/94a7e3b59ef75b0e883ef7a63feba75e53d67807/projects/primeng-shadowdom-directives/src/directives/dropdown.ts#L5-L23)

About this I have two follow-up questions:

1. What is the difference between your `bindScrollListener` and [the original](https://github.com/primefaces/primeng/blob/1571057453d3031b70f23a74210e4541289834ad/src/app/components/dropdown/dropdown.ts#L1251-L1261)? They look identical to me - it seems this part of your code could be deleted, is this correct?

2. I think I've found a corner case to [your code here](https://github.com/maitrungduc1410/primeng-shadowdom-directives/blob/94a7e3b59ef75b0e883ef7a63feba75e53d67807/projects/primeng-shadowdom-directives/src/directives/dropdown.ts#L18-L22). I see that `event.target.shadowRoot ? path[0] : event.target` guarantees that `target` is the lowest possible descendant that was clicked (excluding closed-mode shadow roots). However, the last line of code in that function still uses `nativeElement.contains(target)` to check, and what if there is another ShadowDom boundary between `nativeElement` and `target`?

For item 2, I propose another modification, that is to stop using the built-in `nativeElement.contains()` function and replace it with a custom function that actually walks across ShadowDom boundaries, what do you think? (The reason I'm not 100% sure is that I am wondering if ShadowDom should interfere somehow in the concept of 'outside click' for this case)

**Comment by maitrungduc1410** [comment]
> What is the difference between your bindScrollListener and [the original](https://github.com/primefaces/primeng/blob/1571057453d3031b70f23a74210e4541289834ad/src/app/components/dropdown/dropdown.ts#L1251-L1261)? They look identical to me - it seems this part of your code could be deleted, is this correct?

good question, yes, from your perspective, it looks identical I just use exactly same logic, but import my [connectedoverlayscrollhandler](https://github.com/maitrungduc1410/primeng-shadowdom-directives/blob/master/projects/primeng-shadowdom-directives/src/directives/autocomplete.ts#L3) (which imports my `domhandler.ts` where I handle ShadowDOM)

**Comment by maitrungduc1410** [comment]
for the number 2: when I create this library, what I try to do is to solve the issue with Shadow DOM, keep logics as closest to the original from PrimeNG as possible. Which one you pointed out, it's [original code](https://github.com/primefaces/primeng/blob/master/src/app/components/dropdown/dropdown.ts#L692-L694) from primeNG

So in my code I just add more cases to check, **without** changing original logics of PrimeNG.

I'd like to keep it close to PrimeNG, that makes it easier for upgrading to later version of PrimeNG in the future

**Comment by papb** [comment]
> So in my code I just add more cases to check, **without** changing original logics of PrimeNG.

In a sense you are changing the original logic, slightly, since your code replaces what was `event.target` with the deepest possible descendant. I understand your idea of keeping it close to PrimeNG, it's a good idea, but of course you need to make the changes for ShadowDom, obviously. In other words, you want to change _only what's necessary_, and I agree with that.

> For item 2, I propose another modification, that is to stop using the built-in `nativeElement.contains()` function and replace it with a custom function that actually walks across ShadowDom boundaries, what do you think?

I think the above may be necessary, what do you think?

**Comment by maitrungduc1410** [comment]
understand your idea, just went through your comment [here](https://github.com/primefaces/primeng/issues/9471#issuecomment-1220016648)

I think I'll update the library, to override `getScrollableParents` and `getParents` directly from the module `primeng/dom`, it'll look something like:
```js

import { DomHandler } from 'primeng/dom'

DomHandler.getScrollableParents = (element: any) => {

}
```
So that I don't need to keep 2 files `connectedoverlayscrollhandler.ts` and `domhandler.ts`

**Comment by maitrungduc1410** [comment]
> I think the above may be necessary, what do you think?

`nativeElement.contains()` works okay in Real DOM and ShadowDOM, using it makes behaviours same no matter where we're in Real DOM or shadow DOM, if we change in either side we should change in the other also, what i mean is if we change in Shadow DOM , we should change the behaviour in Real DOM also -> out of sync with PrimeNG logics

**Comment by papb** [comment]
> `nativeElement.contains()` works okay in Real DOM and ShadowDOM,

Are you sure? After a quick test here, I did `A -> B -> ShadowRoot -> C` and `A.contains(C)` returned `false`

**Comment by maitrungduc1410** [comment]
can u give me an example ? (Eg: stackblitz, code sandbox,...)

**Comment by papb** [comment]
@maitrungduc1410 Here: https://codesandbox.io/s/native-contains-vs-shadow-root-e5o8l4?file=/index.html

**Comment by papb** [comment]
Note: I have to go now, I'll come back to this in about 10 hours or so. Thank you very much for your attention and good work :)

**Comment by maitrungduc1410** [comment]
Just checked your example, understand your point. Your demo is to render host element in real dom and child in ShadowDOM, but it's not the case of primeNG component here.

2 things I need to highlight.

First and most important thing to notice: you need to focus in our case, where we render PrimeNG component inside shadow DOM, and there's issue when displaying "overlay" at the component position:
- If the component is displayed in Shadom DOM, and its overlay displays in same ShadowDOM -> they're in same environment (under same shadowRoot) -> `contains` works -> my code works
- If the overlay is displayed in body (`appendTo` body) -> my code still works

Second thing, your code has a `while` loop to find target element, in case of a real web app this can easily lead to  heavy loop since we can have many + nested elements, it'll block the UI since you run in main thread.

All in all, I think my code should work fine, in this case (as PrimeNG component)

**Comment by papb** [comment]
> * If the overlay is displayed in body (`appendTo` body) -> my code still works

Can you clarify why you're sure your code still works in this case?

**Comment by maitrungduc1410** [comment]
as you see [here](https://github.com/maitrungduc1410/primeng-shadowdom-directives/blob/94a7e3b59ef75b0e883ef7a63feba75e53d67807/projects/primeng-shadowdom-directives/src/directives/dropdown.ts#L18-L22), all the computations are done using current event path / event target + hostEl. And 2 of them are always inside a same root (document root if Real DOM, ShadowRoot if in Shadow DOM)

So in general, I'm not seeing any case where it's like your example: event target and its root are not in same environment (based on my code)
