### ISSUE TITLE
Question: version compatible with angular 8?

### ISSUE THREAD

**Issue by darekpham** [maitrungduc1410/primeng-shadowdom-directives#9]
Firstly, I would like to say thank you for this useful library .

We used the lib in our project with angular v13 and it working well. But we also want to apply to other project with old angular v8 (no possibility to ugrade to higher version). We are facing issues like below:

`../node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.`
`static ɵdir: i0.ɵɵDirectiveDeclaration<psdAutoCompleteDirective, "[psdAutoComplete]", never, {}, {}, never>;`

Do you have a plan to publish version compatible with angular 8 too?

**Comment by maitrungduc1410** [comment]
Hi,

I don't have plan to support Angular version which is too old, since its takes much effort.

From what I see, Angular is not good in term of backward compatibility, from Angular 12->13 it's major breaking change already.

In your case it's Angular 8 :), it's definitely a challenge.

Another reason is I believe you're using quite old version of PrimeNG. Then I'll need to make custom build to adjust my lib for different version of primeNG also (in your case).

As you can see, too much overhead. So I'd better to keep my lib supports latest version of Angular only (~ >= 11)

**Comment by darekpham** [comment]
I see, it's definetly too much work.
Btw, thank you for the quick answer.
